[package]
name = "test_three"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cnsl = "0.1.3"
named_tuple = "0.1.3"
