[package]
name = "creo_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.1"
winreg = "0.52"
yaml-rust2 = "0.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
